CREATE TABLE IF NOT EXISTS Auth(
  lid SERIAL8 PRIMARY KEY,
  login TEXT UNIQUE NOT NULL
    CHECK (LENGTH(login) >= 3 AND login ~ E'^[a-zA-Z][-a-zA-Z0-9_@\\.]*$'),
  email TEXT DEFAULT NULL CHECK (email IS NULL OR email ~ E'@'),
  mobile TEXT NOT NULL, 
  password TEXT NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  isAdmin BOOLEAN DEFAULT FALSE,
  unom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  pictures TEXT DEFAULT './static/images/mug-koala.jpg'
);

CREATE TABLE IF NOT EXISTS categorie(
    cid SERIAL PRIMARY KEY,
    cnom TEXT NOT NULL,
    UNIQUE(cnom)
);

CREATE TABLE IF NOT EXISTS EstExpert(
    cid INTEGER NOT NULL REFERENCES categorie ON DELETE CASCADE,
    lid INTEGER NOT NULL REFERENCES Auth ON DELETE CASCADE,
    UNIQUE(cid,lid)
);

CREATE TABLE IF NOT EXISTS objet(
    oid SERIAL PRIMARY KEY,
    dispo INTEGER DEFAULT 0,
    onom TEXT NOT NULL,
    lid INTEGER NOT NULL REFERENCES Auth ON DELETE CASCADE,
    cid INTEGER DEFAULT NULL REFERENCES categorie ON DELETE CASCADE,
    pictures TEXT DEFAULT NULL,
    UNIQUE(lid,oid)
);

CREATE TABLE IF NOT EXISTS action(
    lid INTEGER NOT NULL REFERENCES Auth ON DELETE CASCADE,
    oid INTEGER NOT NULL REFERENCES objet ON DELETE CASCADE,
    action_id INTEGER NOT NULL,
    debut TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fin TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS groupe(
    gid SERIAL PRIMARY KEY,
    gnom TEXT NOT NULL,
    UNIQUE(gnom)
);

CREATE TABLE IF NOT EXISTS appel(
    aid SERIAL PRIMARY KEY,
    lid INTEGER NOT NULL REFERENCES Auth ON DELETE CASCADE,
    cid INTEGER NOT NULL REFERENCES categorie ON DELETE CASCADE,
    onom TEXT NOT NULL,
    date_appel TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(lid,cid,onom)
);

CREATE TABLE IF NOT EXISTS appartient(
    gid INTEGER NOT NULL REFERENCES groupe ON DELETE CASCADE,
    lid INTEGER NOT NULL REFERENCES Auth ON DELETE CASCADE,
    UNIQUE(gid,lid)
);
